spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port: 9900